version: 0.2

env:
    variables:
        REACT_APP_DB: "http://http://storageappserve-env.eba-mbwru5ty.eu-west-1.elasticbeanstalk.com/"

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm run build

artifacts:
    files:
        - "**/*"
    base-directory: build
